### PR TITLE
Remove Google Analytics

### PR DESCRIPTION
**Pull request by resynth1943**
Would you be willing to remove this Google Analytics 'functionality' from this website? There are better alternatives if you *must* keep tabs on users' activity.

Some reputable alternatives can be seen here: https://switching.software/replace/google-analytics/

### CODE REVIEW

**Comment by KennethL** [comment]
Google Analytics is not used at all for this site an pages. The analytics.html is just there as an example that come with the use of Jekyll. To activate Google analytics is must be configured in the _config.yml file which it is not. So the OTP blog is totally free from analytics AFIK.

**Comment by resynth1943** [comment]
Excuse me, but I have seen Google Analytics in use in your documentation. Your team does use Google Analytics. Would you care to direct me to the source code for the documentation pages, please?

**Comment by KennethL** [comment]
yes in the documentation we are using Google analytics, started for more
than 10 years I think.

I have never thought of that Google can collect info about individual
users, since we are only interested in what pages are most visited and from
where the visitors are.

So you and others have problems with Googles possibilities here?

Regards Kenneth

**Comment by TheEvilSkeleton** [comment]
> So you and others have problems with Googles possibilities here?

tbh yes, Google is known to collect users' data without their consent as well as monopolizing, (and other obvious stuff). i second this merge request, it keeps Google from taking too much power in this world. also, Matomo has its own page comparing Matomo analytics to Google Analytics:

- https://matomo.org/matomo-vs-google-analytics-comparison/

EDIT: and Google Analytics is proprietary anyway, so that alone is a bad thing IMO

**Comment by resynth1943** [comment]
> I have never thought of that Google can collect info about individual
users, since we are only interested in what pages are most visited and from
where the visitors are.

Yeah. Although I can't say for certain, there's a very high probability that Google use Google Analytics to gain a sort of *browsing history* for a specific user. This helps them build an ad profile on said user. 

*Why do they really offer Analytics for free?*

**Comment by RossComputerGuy** [comment]
Google's main thing is advertisement. They generate search results from data they gather. It's basically a big spider web of sites and software that powers Google's search and ads. If you even have a single Google user signed in then it could be collecting data. If you don't have anyone signed into Google on that browser, it may still try linking you up to your account through other means. I have no idea what Google is capable of but we should assume it could basically link you up to stuff easily.

**Comment by resynth1943** [comment]
I'm guessing that Google Analytics and Google DNS are used to contain a user's browsing history. Then that's paired up with Search for 'personalisation'.

**Pull request closed without merging**
